<?php
if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true) die();

use Bitrix\Main\Localization\Loc as Loc;
use Rekuital\BitrixComponentParameters\ComponentParameterFactory;
use Rekuital\BitrixComponentParameters\Enum\FileTargetTypeEnum;

Loc::loadMessages(__FILE__);

require_once realpath(__DIR__.'/../../../vendor/autoload.php');

$builder = ComponentParameterFactory::createComponentParamsBuilder()
    ->addParameterAjaxMode()
    ->addParameterCacheTime()
    ->addParameterSetTitle()
    ->addParameterUserConsent()
    ->addGroupBuilder('CUSTOM', 'Своя группа параметров', 1000)
    ->addParameterCheckbox('TEST_CHECKBOX', 'Тестовый чекбокс')
    ->setRefresh()
    ->setDefaultValue('Y')
    ->complete()
    ->addParameterCustom('TEST_CUSTOM', 'Тестовый кастомный параметр')
    ->setDefaultValue('2025-11-01')
    ->setJsEvent('onLoadParameters')
    ->setJsFile('/local/components/project/example.list/settings/custom_parameter.js')
    ->setJsData(['style' => 'color: green;'])
    ->complete()
    ->addParameterFile('TEST_FILE', 'Тестовый файл')
    ->setTarget(FileTargetTypeEnum::FILE)
    ->setExtensions(['png', 'jpg'])
    ->addExtension('mp4')
    ->setMediaLibTypes(['image'])
    ->addMediaLibType('video')
    ->complete()
    ->addParameterList('TEST_LIST', 'Тестовый список')
    ->setDefaultValue('OPTION_1')
    ->setRefresh()
    ->setSize(5)
    ->setMultiple()
    ->setHasAdditionalValue()
    ->setWidthField(100)
    ->setVariantsList(['OPTION_1' => 'опция 1', 'OPTION_2' => 'опция 2'])
    ->addVariant('OPTION_3', 'опция 3')
    ->addVariant('OPTION_4', 'опция 4')
    ->addVariant('OPTION_5', 'опция 5')
    ->addVariant('OPTION_6', 'опция 6')
    ->complete()
    ->addParameterString('TEST_STRING', 'Тестовый строковый параметр')
    ->setWidthField(100)
    ->setMultiple()
    ->setRefresh()
    ->setDefaultValue(['Тест'])
    ->complete()
    ->addParameterColorpicker('TEST_COLOR', 'Тестовый выбор цвета')
    ->setDefaultValue('EEE')
    ->setRefresh()
    ->complete()
    ->complete()
    ->addGroupBuilderBase()
    ->addParameterString('TEST_STRING_PARAM', 'Тестовый параметр')
    ->complete()
    ->complete()
    ->addGroupBuilderAdditionalSettings()
    ->addParameterCheckbox('TEST_AdditionalSettings', 'Тест AdditionalSettings')
    ->complete()
    ->complete()
    ->addGroupBuilderAjaxSettings()
    ->addParameterCheckbox('TEST_AjaxSettings', 'Тест AjaxSettings')
    ->complete()
    ->complete()
    ->addGroupBuilderCacheSettings()
    ->addParameterCheckbox('TEST_CacheSettings', 'Тест CacheSettings')
    ->complete()
    ->complete()
    ->addGroupBuilderDataSource()
    ->addParameterCheckbox('TEST_DataSource', 'Тест DataSource')
    ->complete()
    ->complete()
    ->addGroupBuilderUserConsent()
    ->addParameterCheckbox('TEST_UserConsent', 'Тест UserConsent')
    ->complete()
    ->complete()
    ->addGroupBuilderVisual()
    ->addParameterCheckbox('TEST_Visual', 'Тест Visual')
    ->complete()
    ->complete()
;

$arComponentParameters = $builder->create();